name = "StructReinterpret"
uuid = "4d2720c4-0d11-11e9-387d-8be1255854ec"
authors = ["Felipe Alves <favbalves@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
